### ISSUE TITLE
Consul api gateway on vm based installation

### ISSUE THREAD

**Issue by thatsk** [hashicorp/consul-api-gateway#102]
Consul api gateway installation and configuration should be on vm based installation also which is binary based itself.
Otherwise it will only stick to k8s not with vm based workloads

**Comment by thatsk** [comment]
so we are basically using centos7 with consul binary and we have nomad based workload for container and we are not using k8s. and we are using basically f5 for loadbalancer.

**Comment by ashwinkupatkar** [comment]
Yes we need support for consul api gateway for VM based workloads.

**Comment by thatsk** [comment]
Eagerly waiting for this feature

**Comment by Esity** [comment]
@Jeff-Apple Looking for an update on this one also. Would be useful to allow for things like VMs and Nomad(issue #209) to expand more use cases. Only allowing K8s limits adoption of the api gateway IMO

CC @wjpatton

**Comment by thatsk** [comment]
So are we talking this in quarter

**Comment by Esity** [comment]
@Jeff-Apple  is there an update on this one?

**Comment by Esity** [comment]
Still looking for an update on this one

**Comment by Esity** [comment]
For anyone watching this issue, sounds like this is slated for the Consul 1.15 release

**Comment by andrewstucki** [comment]
Closing as we're releasing beta support for using API gateways as a native Consul gateway type that can be run in non-Kubernetes workloads in 1.15 🎉
