### ISSUE TITLE
make ctrl-generate removes config from dev/config/helm/consul.yaml

### ISSUE THREAD

**Issue by mikemorris** [hashicorp/consul-api-gateway#108]
### Reproduction Steps

Running `make ctrl-generate` creates the diff below, which appears to remove a significant amount of custom Consul config. Either the generation source is out of date, or this Makefile command should be removed if the content of this file should no longer be auto-generated.

### Expected behavior

Generated code should always be kept in sync with the source, and running `make ctrl-generate` or other code generation commands should be a no-op unless corresponding changes are made to the source (refs https://github.com/hashicorp/consul-api-gateway/pull/93).

### Additional Context

```
diff --git a/dev/config/helm/consul.yaml b/dev/config/helm/consul.yaml
index d6bce35..e6e5580 100644
--- a/dev/config/helm/consul.yaml
+++ b/dev/config/helm/consul.yaml
@@ -1,41 +1,11 @@
-global:
-  name: consul
-  image: "hashicorpdev/consul:581357c32"
-  tls:
-    enabled: true
-    serverAdditionalDNSSANs:
-    - host.docker.internal
-    - localhost
-    - consul-server.default.svc.cluster.local
+client:
+  enabled: true
+  exposeGossipPorts: true
+  join:
+    - "127.0.0.1"
+  hosts:
+    - "127.0.0.1"
 connectInject:
   enabled: true
 controller:
   enabled: true
-server:
-  replicas: 1
-  extraConfig: |
-    {
-      "log_level": "trace",
-      "acl": {
-        "enabled": true,
-        "default_policy": "allow",
-        "enable_token_persistence": true
-      },
-      "connect": {
-        "enabled": true
-      }
-    }
-ui:
-  enabled: true
-  ingress:
-    enabled: true
-    hosts:
-    - host: "host.docker.internal"
-      paths:
-      - "/"
-    - host: "localhost"
-      paths:
-      - "/"
-    annotations: |
-      "kubernetes.io/ingress.class": "nginx"
-      "nginx.ingress.kubernetes.io/ssl-passthrough": "true"
```

**Comment by nathancoleman** [comment]
@mikemorris I can't reproduce this myself. Curious what version of `controller-gen` you have.

```bash
$ controller-gen --version
Version: v0.6.0
```

**Comment by mikemorris** [comment]
Also using `v0.6.0` of `controller-gen`, but can't reproduce this any longer - possibly just hit this due to switching between an older branch and `main` or something.
