### ISSUE TITLE
API Gateway deployment in AKS using Helm

### ISSUE THREAD

**Issue by mdaslamansari** [hashicorp/consul-api-gateway#122]
### Overview of the Issue

unable to recognize "": no matches for kind "GatewayClass" in version "gateway.networking.k8s.io/v1alpha2", unable to recognize "": no matches for kind "GatewayClassConfig" in version "api-gateway.consul.hashicorp.com/v1alpha1"][0m

**Comment by nathancoleman** [comment]
Hi @mdaslamansari . It looks to me like the Gateway CRDs are missing in the cluster. Did you have a chance to install those before installing the Helm chart?

[Source](https://www.consul.io/docs/api-gateway/api-gateway-usage#installation):
```shell
$ kubectl apply --kustomize="github.com/hashicorp/consul-api-gateway/config/crd?ref=v0.1.0"
```

**Comment by nathancoleman** [comment]
@mdaslamansari I'm going to close this for now. If you're still encountering issues after trying the steps above, please feel free to reopen.
