### ISSUE TITLE
Consul API Gateway pods keep being re-created

### ISSUE THREAD

**Issue by matsyy** [hashicorp/consul-api-gateway#594]
Hello :)

### Overview of the Issue

When deploying the Consul API Gateway: https://www.consul.io/docs/api-gateway/api-gateway-usage#installation, the related Deployment / Pods `api-gateway-xxxxxxxxx-xxxxx` keep being terminated and created.

### Reproduction Steps

I followed the tutorial: https://developer.hashicorp.com/consul/tutorials/kubernetes/kubernetes-api-gateway (self-managed, Helm).

1. Install Consul :

With `apiGateway` stanza commented in `values.yaml`:

(values.yaml)
```
global:
  enabled: true
  name: consul
  datacenter: dc1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
server:
  enabled: true
  replicas: 1
ui:
  enabled: true
  service:
    type: NodePort
# apiGateway:
#   enabled: true
#   image: "hashicorp/consul-api-gateway:0.5.1"
#   managedGatewayClass:
#     serviceType: NodePort
#     useHostPorts: true
```

```
helm repo add hashicorp https://helm.releases.hashicorp.com
helm repo update hashicorp

helm install --values consul/values.yaml consul hashicorp/consul --create-namespace --namespace consul
```

I first comment the `apiGateway` stanza because I get the following error message otherwise:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "consul-api-gateway" namespace: "" from "": no matches for kind "GatewayClass" in version "gateway.networking.k8s.io/v1alpha2"
ensure CRDs are installed first, resource mapping not found for name: "consul-api-gateway" namespace: "" from "": no matches for kind "GatewayClassConfig" in version "api-gateway.consul.hashicorp.com/v1alpha1"
ensure CRDs are installed first]
```

2. Create the CRDs :

`kubectl apply --kustomize "github.com/hashicorp/consul-api-gateway/config/crd?ref=v0.5.1"`

3. Uncomment the `apiGateway` stanza in `values.yaml`.

`helm upgrade --values consul/values.yaml consul hashicorp/consul --create-namespace --namespace consul`

4. Deploy Hashicups and Echo apps :

`kubectl apply --filename two-services/`

5. Déployer l'API Gateway Consul :

`kubectl apply --filename api-gw/consul-api-gateway.yaml`

### Logs

`kubectl logs` on the API Gateway controller pod displays:

```
[ERROR] k8s/logger.go:35: consul-api-gateway-server.controller-runtime: Reconciler error: Gateway=consul/api-gateway controller=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway name=api-gateway namespace=consul reconcileID=62f3ae49-ed3f-4f5a-908f-2879f94ba910
  error=
  | 1 error occurred:
  | \t* Operation cannot be fulfilled on gateways.gateway.networking.k8s.io "api-gateway": the object has been modified; please apply your changes to the latest version and try again
  |
```

### Expected behavior

A Consul API Gateway Service ready and operational.

### Environment details

If not already included, please provide the following:
- `consul-api-gateway` version: 0.5.1
- configuration used to deploy the gateway controller:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
  namespace: consul
spec:
  gatewayClassName: consul-api-gateway
  listeners:
  - protocol: HTTPS
    port: 8443
    name: https
    allowedRoutes:
      namespaces:
        from: All
    tls:
      certificateRefs:
        - name: consul-server-cert
```

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.27.3
- Consul Server version: v1.16.0
- Consul-K8s version: 1.2.0
- Minikube: 1.31.1 (default configuration)

Thank you for the help :)

**Comment by t-eckert** [comment]
Hi @matsyy, thank you for opening an issue. For a new deployment, we definitely recommend using the new "Native" implementation, but the tutorial does not yet reflect that.

Instead of using the `apiGateway` stanza at the root, simply omit it as the API Gateway controller now runs by default. Consul will also install the needed CRDs by default as well. 

Change the `gatewayClassName` to `consul` and you should be all set. Feel free to check in again if you get stuck!

**Comment by matsyy** [comment]
Hi @t-eckert, thank you very much for the quick answer!

I was already told that I should not use the `apiGateway` stanza at the root but `connectInject` stanza instead to enable and configure the API Gateway, after reporting another [issue](https://github.com/hashicorp/consul-k8s/issues/2715) in consul-k8s repo.

Following the advice, I could not see any controller starting so I had a look at the tutorial I mentionned to figure out why.

I will try to change the `gatewayClassName` value to `consul` and I will update the current issue after that.

**Comment by t-eckert** [comment]
That would be confusing. We integrated that controller code into the controller that manages service mesh for Consul on Kubernetes. 

Here is an updated tutorial that I hope you find helpful: https://developer.hashicorp.com/consul/tutorials/get-started-kubernetes/kubernetes-gs-ingress

**Comment by matsyy** [comment]
Hello @t-eckert, it worked: the API Gateway is running without being deleted and recreated. Thank you for the support.
